name: etiya_assignment
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  #stateManagement
  mobx: ^2.1.3
  flutter_mobx: ^2.0.6+5
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  #network
  dio: ^4.0.6

  #permission
  permission_handler: ^10.2.0

  #route
  auto_route: ^4.2.1


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  build_runner: ^2.1.11
  json_serializable: ^6.2.0
  auto_route_generator: ^4.0.0
  hive_generator: ^1.1.3
  mobx_codegen: ^2.0.7

  flutter_lints: ^2.0.0

flutter:

  assets:
    - assets/cities/

  uses-material-design: true

  
